@startuml
WebWorker -> 主线程: 传递创建Camera使用的参数
主线程 -> 主线程: 创建一个一样的Camera对象
主线程 -> 主线程: 创建OrbitControls控制器
主线程 -> Camera代理: 对代理的Camera做操作
Camera代理 -> WebWorker: 通过.postMessage方法传递修改的参数
WebWorker -> WebWorker: 将修改同步到自己的Camera对象中
WebWorker -> WebWorker: 使用修改后的Camera对象进行渲染
@enduml
